# -*- mode: ruby -*-
# vi: set ft=ruby :

ip = '192.168.42.110'
server_name = 'mmeskiS' 

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  config.vm.define server_name do |server|
    server.vm.network "private_network", ip: ip
    server.vm.hostname = server_name
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      end
    server.vm.provision "shell" do |s|
      s.path = 'scripts/server.sh'
    end
  end

end
