# -*- mode: ruby -*-
# vi: set ft=ruby :

# need 2 machine with last centos
# 1 cpu 1024 of ram 
# ip of server 192.168.42.110
# ip of server worker 192.168.41.111

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "mmeskiS" do |server|
    server.vm.network "private_network", ip: "192.168.42.110"
    server.vm.hostname = "mmeskiS"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      end
      server.vm.provision "shell" do |s|
        s.path = "s_setup.sh"
      end
    end
    config.trigger.after :up do |trigger|
      trigger.run = {inline: "vagrant scp mmeskiS:/home/vagrant/token ./"}
      
    end
  config.vm.define "mmeskiSW" do |worker|
    worker.vm.network "private_network", ip: "192.168.42.111"
    worker.vm.hostname = "mmeskiSW"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      end
      worker.vm.provision "shell" do |s|
        s.path = 'sw_setup.sh'
      end
    end
end